models:
  - name: dim_movies
    description: Dimension table for cleaned movie metadata
    columns:
      - name: movie_id
        description: Primary key of the movie
        test:
          - unique
          - not_null
      - name: movie_title
        description: Standardized movie
        test:
          - not_null
      - name: genre_array
        description: List of genres in array format
      - name: genres
        description: Raw genres string from sources

  
  - name: dim_users
    description: Dimension table of unqie users from both ratings
    columns:
      - name: user_id
        description: Unique user identifier
        test:
          - not_null

  - name: dim_genome_tags
    columns:
      - name: tag_id
        description: Unique tag id
        test:
          - unique
          - not_null
      - name: tag_name
        description: human-readable tag name
        tests:
          - not_null

  - name: fact_ratings
    description: Fact table of user ratings for movies
    columns:
      - name: user_id
        description: Foreign key to dim_users
        tests:
          - not_null
      - name: movie_id
        description: Foreign key to dim_movies
        tests:
          - not_null
          - relationships:
              to: ref('dim_movies')
              field: movie_id
      - name: rating
        description: User's rating for a movie
        tests: 
          - not_null
      - name: rating_timestamp
        description: Unix timestamp when the rating was made

  - name: fact_genome_scores
    description: Fact table of relevance scores per movie and tag
    columns:
      - name: movie_id
        description: Foreign key to dim_movies
        tests:
          - not_null
      - name: tag_id
        tests:
          - not_null
      - name: relevance_score
        -tests:
          - not_null
          